### ISSUE TITLE
So many errors (with error code  CS0246,CS0234,CS0115) even after importing the SDK 

### ISSUE THREAD

**Issue by GhaithxSW** [AgoraIO-Extensions/Agora-Unity-Quickstart#115]
![AgoraErrs](https://user-images.githubusercontent.com/108682805/191271743-6af6ebaa-5506-4dfa-ad88-341e2ae38236.PNG)

**Comment by xiayangqun** [comment]
1. you can download our sdk Unity-v4.0.0-rc1 from this url (https://docs.agora.io/en/All/downloads?platform=All%20Platforms#SDK%20Downloads)
2. checkout branch main in this git 
3. import sdk Unity-v4.0.0-rc1 into Unity project

**Comment by GhaithxSW** [comment]
Thank you it worked, but now after building I get that error when trying to jump to any API,

![AgoraWebGLErr](https://user-images.githubusercontent.com/108682805/191721419-426ab740-d9a6-4f02-a586-49295ff3c73e.PNG)
![AgoraConsoleErr](https://user-images.githubusercontent.com/108682805/191721428-1114d0ba-4d9b-42d3-9b7c-b976430d068f.PNG)

**Comment by xiayangqun** [comment]
Sorry , We are you support WebGL yet.
