### ISSUE TITLE
Unity Android and iOS (possible) phone overheat

### ISSUE THREAD

**Issue by LoopIssuer** [AgoraIO-Extensions/Agora-Unity-Quickstart#203]
I'm using Agora SDK (together with MediaPipe Unity Plugin), everything works fine. Unfortunately, our client believes that the application overheats the phone (Android and iOS) too quickly (does not provide data) and users therefore resign from using it.
Is there anything that can be done to make the phones less hot and drain less battery?

Thanks in advance

**Comment by xiayangqun** [comment]
Reduce the resolution and frame rate of the video, which will reduce power consumption
