### ISSUE TITLE
A lot of errors when starting with UnityEditor.

### ISSUE THREAD

**Issue by KazukiKuriyama** [AgoraIO-Extensions/Agora-Unity-Quickstart#262]
I have launched the project in this repository with Unity2018.4.0f1, but I get an error as shown in the attached image.
Can you please let me know how to deal with this error?

![image (1)](https://github.com/AgoraIO-Extensions/Agora-Unity-Quickstart/assets/64897247/809eb057-b204-48a5-89f2-038070d2649e)

**Comment by xiayangqun** [comment]
you can download agora rtc unity sdk from here

https://docs.agora.io/en/sdks?platform=unity

and this unitypackage include all api-example into it.All you need to do is import this unitypackage file into a empty unity project and then you can find api-example folder in it.

**Comment by KazukiKuriyama** [comment]
@xiayangqun 
Does that mean this repository alone won't work?

**Comment by xiayangqun** [comment]
yes, it is. And you need import agora unity rtc sdk to use it.
You can get more information from readme.md

https://github.com/AgoraIO-Extensions/Agora-Unity-Quickstart/blob/v4.3.2/API-Example-Unity/README.md

**Comment by KazukiKuriyama** [comment]
@xiayangqun 

Have you actually imported the SDK into this repository to make sure it works?

I got this VideoSDK from here and imported it, but the error still appears.

https://docs.agora.io/en/sdks?platform=unity

**
![image](https://github.com/AgoraIO-Extensions/Agora-Unity-Quickstart/assets/64897247/a2a91cf4-0884-411e-abe5-339cdb94b0ec)
**

**Comment by xiayangqun** [comment]
This is beacuse of this repository include rtm example. But sdk only have rtc code.
 I suggest you dont clone any code from this repository. You can run example with the sdk you download from https://docs.agora.io/en/sdks?platform=unity

1. Just create an empty project with unity editor
2. Import sdk form https://docs.agora.io/en/sdks?platform=unity you download
3. You can find all example(only with rtc, but not rtm) in Assets/Agora-RTC-Plugin/API-Example

**Comment by KazukiKuriyama** [comment]
@xiayangqun 
I understand that the sample Scene on this repository does not work.



The following is a change of subject from this Issue.



So, does it definitely work with the current latest version of SDK 4.3.2?
If not, can you tell us which version of the SDK you have actually tested working on Unity? If possible, I would also like to know the version of Unity at that time.

As I have asked in the Slack channel below, only the Spatial Audio functionality is not working in my environment using the Agora VideoSDK.
I would like to know in which environment it works.

https://agoraiodev.slack.com/archives/CFDG7Q6F6/p1717652209783499
