### ISSUE TITLE
How to resolve the error : - [d3d11] attempting to ReadPixels outside of RenderTexture bounds! Reading (0, 0, 215, 383) from (215, 382) ?

### ISSUE THREAD

**Issue by praveenjha-github** [AgoraIO-Extensions/Agora-Unity-Quickstart#48]
Hi,
I am trying to broadcast my video through UnityRuntime on a particular App Id and Token and Channel which i have temporary created from Agora.Io.
Issue, which i am facing is the error D3D11.i have also shared the screenshot for that.

![error](https://user-images.githubusercontent.com/86768166/156146622-7e85c9e1-6c55-470e-8390-94a724872c7c.jpg)

and on the Browser side if i see by clicking on AgoraWebDemos, is this screen which is coming as total white.

![window](https://user-images.githubusercontent.com/86768166/156146812-80924df1-f81a-434a-8300-c2d7d6b484ca.jpg)

I am new to Agora, so please help me to get this error resolved.

I have also made my script which is similar as the script which you posted it to Agora Github which is : - 

https://github.com/AgoraIO/Agora-Unity-Quickstart/blob/master/API-Example-Unity/Assets/API-Example/examples/advanced/ScreenShareOnMobile/AgoraScreenShare.cs

Any Help will be appreciated.

**Comment by icywind** [comment]
@praveenjha-github , we didn't see a screenshot of the error shared.  Can you copy and paste what exact error is?

**Comment by D3WN** [comment]
Scenes窗口 ，不要选择2D，试试看~
