### ISSUE TITLE
initialize engine fail

### ISSUE THREAD

**Issue by wayhow123** [AgoraIO-Extensions/Agora-Unity-Quickstart#79]
init failed when call IRtcEngine.GetEngine(appId);

Create engine failed, error code: -7
UnityEngine.Debug:LogError (object)
agora_gaming_rtc.IRtcEngine:.ctor (string) (at Assets/AgoraSDK/Scripts/AgoraGamingSDK/AgoraGamingRtcEngine.cs:240)
agora_gaming_rtc.IRtcEngine:GetEngine (string) (at Assets/AgoraSDK/Scripts/AgoraGamingSDK/AgoraGamingRtcEngine.cs:4985)
AgoraVideoChatController:<Start>b__5_0 () (at Assets/Scripts/AgoraVideoChatController.cs:29)

why error code is -7????

**Comment by icywind** [comment]
The Readme file has the answer for you.  See this section:
![README_QuickStart_pdf](https://user-images.githubusercontent.com/1261195/175721682-f0445a18-a8ab-41c8-8c0c-0e0cc5619f61.png)
