### ISSUE TITLE
音频在ipad pro上会导致声音变成听筒模式

### ISSUE THREAD

**Issue by wayhow123** [AgoraIO-Extensions/Agora-Unity-Quickstart#85]
音频在ipad pro上会导致声音变成听筒模式

**Comment by xiayangqun** [comment]
public override int SetDefaultAudioRouteToSpeakerphone(bool defaultToSpeaker)
 maybe you can call RtcEngine.SetDefaultAudioRouteToSpeakerphone(false/true) to solve this issue

**Comment by wayhow123** [comment]
> public override int SetDefaultAudioRouteToSpeakerphone(bool defaultToSpeaker) maybe you can call RtcEngine.SetDefaultAudioRouteToSpeakerphone(false/true) to solve this issue

早就试过了并没有什么用

**Comment by plutoless** [comment]
@wayhow123 这边之前尝试是在什么时候调用的? 能提供一份日志吗
