### ISSUE TITLE
Can not open Example Scene with 2019 or 2020

### ISSUE THREAD

**Issue by ttkrpink** [AgoraIO-Extensions/Agora-Unity-Quickstart#89]
2019.4.40f1c1 Error:

![image](https://user-images.githubusercontent.com/2522889/175972400-e099d6aa-09c4-4907-8fef-34292a534c0d.png)

After "Cancel": 
![image](https://user-images.githubusercontent.com/2522889/175973731-66054bd5-ccf3-4935-a5d4-5016ce559658.png)

2020.3.25f1c1 Error:

![image](https://user-images.githubusercontent.com/2522889/175974990-e2784f73-c2a7-486b-9865-56a4c53efd83.png)

Thanks for your help

**Comment by xiayangqun** [comment]
Questions1:
This example is base on Unity 2017.3.  when you use Unity 2019 or 2020. There is some diff in ProjectSettings folder. There is a suggest.
1. close your Unity Editor.
2. delete ProjectSettings folder
3. reopen project with Unity 2019 or 2020
4.Unity 2019 or 2020 will create a new ProjectSettins folder.

Questions3:
![企业微信截图_257f956a-4ff9-453d-b170-42adb17fe10e](https://user-images.githubusercontent.com/11383154/176341166-d2993399-4b24-49c1-adad-4c520b01783c.png)

our branch master is adapter with rtc sdk version is 3.7.0.3.  it is look like your download rtc sdk verision is not 3.7.0.3。
may be you should use our example branch 3.5.x.x

**Comment by icywind** [comment]
This issue should now be closed and please upgrade to SDK Version 4.1.0 or up.
