### ISSUE TITLE
Demo演示，3D物体上的视频不会渲染，而UI正常

### ISSUE THREAD

**Issue by 1134451886** [AgoraIO-Extensions/Agora-Unity-Quickstart#93]
![QQ截图20220716160242](https://user-images.githubusercontent.com/40816004/179348735-378a5899-ae76-4432-b661-8bab14bd5b7c.jpg)

**Comment by HugoChaan** [comment]
有几个问题麻烦您解答:您的Editor Console内有打印报错信息么?

**Comment by HugoChaan** [comment]
有几个问题麻烦您解答:
1、您是从官网或Assets Store上下载SDK、引入Unity项目后直接运行demo看到的现象么?
2、unity editor console内有没有什么报错信息?

**Comment by 1134451886** [comment]
1.是的，从官网和Unity的Asset Store都试过了，都是这样的效果
2.只有VideoSurface的debug warning code 8

**Comment by 1134451886** [comment]
然后我查看了源码，把nativetexture设置成公开可以看到只有上面的RawImage组件的nativetexture不为null，其他3D物体的nativetexture都是null，没有生成。

**Comment by 1134451886** [comment]
老哥，help，help
我们抽个时间联调一下怎么样？我们推流直播端，看你那边能否接收正常，你觉得怎么样？

**Comment by HugoChaan** [comment]
可以的, 可以在官网联系Agora的技术支持
