### ISSUE TITLE
Token is Invalid

### ISSUE THREAD

**Issue by gkapellmann** [AgoraIO-Extensions/Agora-Unity-Quickstart#94]
Well, as the title says, I followed the instructions of advance demo and I get: RTC Error:110, msg: The Token is invalid

I have created two apps, one with and one without certificate enabled and nothing changes.

In the demo MainScene, the gamecontroller, there is no place to add the "token".

**Comment by plutoless** [comment]
https://github.com/AgoraIO/Agora-Unity-Quickstart/blob/master/API-Example-Unity/Assets/API-Example/examples/basic/JoinChannelVideo/HelloVideoAgora.cs
i assume the project without token is working for you - above link you can find the place in the c# source to add token value.

**Comment by gkapellmann** [comment]
OK, this is a script in the API-Example-Unity, this has nothing to do with the Advanced Demos, right?

The only way to test the advanced demos is with no certificate enabled?
